- name:  Disable Redis Default Version
  ansible.builtin.shell: dnf module disable redis -y

- name:  Enable Redis 7 Version
  ansible.builtin.shell: dnf module enable redis:7 -y

- name:  Install Redis
  ansible.builtin.dnf:
    name: redis
    state: latest

- name:  Update Redis Config File
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Redis Config File - Update Listen Address
  ansible.builtin.lineinfile:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode'
    line: 'protected-mode no'

- name:  Start Redis Service
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: yes
 