- name: Disable Nginx Default Version
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable Nginx 24 Module
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Setup App Prerequisits
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: Start Nginx Service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true