- name: Disable Nginx Default Version
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable Nginx 24 Module
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

#APP_PREREQ

- name: Start Nginx Service
  ansible.builtin.systemd_service:
    state: started
    name: nginx
    enabled: true