- name: Copy MongoDB repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install rabbitmq server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: latest

- name: Start rabbitmq service
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    status: restarted
    enabled: yest

- name: Create Application User
  ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"