- name: Install GoLang
  ansible.builtin.dnf:
    name: golang
    state: latest

- name: Setup App Prerequisits
  ansible.builtin.include_role:
    name: common
    tasks_from: app-prereq

- name: Download NodeJS Dependencies
  ansible.builtin.shell: go mod init dispatch; go get; go build
  args:
    chdir: "{{ app_path }}"

- name: load Schema
  ansible.builtin.include_role:
    name: common
    tasks_from: schema
  when: schema_setup is defined

- name: Systemd Setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd





